- name: Ubuntu and CentOS configuration
  connection: ssh
  become: true
  gather_facts: true
  hosts: all
  tasks:
    - name: running ubuntu role
      include_role:
        name: ubuntu
      when: ansible_distribution == 'Ubuntu'  
    - name: running centos role
      include_role:
        name: centos
      when: ansible_distribution == 'CentOS'
