---
#tasks file for ubuntu
#Changing Ubuntu hostname needs updating two files which are /etc/hostname & /etc/hosts
#Lineinfile module is used to update the both
#command to check is hostname, but it'll get updated only after rebooting the system
- name: changing System Name in hostname file
  shell: hostnamectl set-hostname "{{ ansible_distribution }}-{{ author_name }}"
- name: changing system name in hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    regexp: '^127\.0\.0\.1'
    backrefs: yes
    line: '127.0.0.1 "{{ ansible_distribution }}_{{ author_name }}"'
# Creating Ansible user
- name: creating ansible user on the system
  ansible.builtin.user:
    name: '{{ item.name }}'
    password: "{{ '{{ item.password }}' | password_hash('sha512')}}"
    groups: "{{ item.groups }}"
    state: present
    shell: "/bin/bash"
    create_home: yes
  with_items: "{{ user_details }}"
# Attaching timestamp to history command
- name: modifying "{{ item }}" file
  lineinfile:
    path: "{{ item }}"
    line: HISTTIMEFORMAT='%F %T'
  with_items: "{{ file_names }}"
#- name: sourcing "{{ item }}" file
#  shell: . "{{ item }}"
#  with_items: "{{ file_names }}"
# Installing packages
- name: Installing packages
  package: 
    name: "{{ item }}" 
    state: latest
  with_items: "{{ packages }}"
  notify: restart services
#Removing ntp package
- name: Removing NTP package
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ r_packages }}"
- name: Reboot the server
  ansible.builtin.reboot:
    reboot_timeout: 3600
- name: Wait for the reboot and reconnect 
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
    timeout: 60
- name: Check the Uptime of the servers
  shell: "uptime"
  register: Uptime
