---
# tasks file for centos
- name: Directory creation
  ansible.builtin.file:
    path: "{{ author_name }}"
    state: directory
    mode: '644'
- name: Installing packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
  notify: restart services
- name: System details
  debug: msg="{{ item }}"
  with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: yes
