---
# handlers file for ubuntu
- name: restart services
  ansible.builtin.service:
    name: '{{ item }}'
    state: restarted
  with_items: '{{ packages }}'
  ignore_errors: yes
- name: Wait for the reboot and reconnect
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
    timeout: 60
